// Code generated by protoc-gen-go. DO NOT EDIT.
// source: entity.proto

package entity

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Entity struct {
	Enabled              bool         `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Class                uint64       `protobuf:"varint,2,opt,name=class,proto3" json:"class,omitempty"`
	Id                   uint64       `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	Components           []*Component `protobuf:"bytes,4,rep,name=components,proto3" json:"components,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Entity) Reset()         { *m = Entity{} }
func (m *Entity) String() string { return proto.CompactTextString(m) }
func (*Entity) ProtoMessage()    {}
func (*Entity) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf50d946d740d100, []int{0}
}

func (m *Entity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Entity.Unmarshal(m, b)
}
func (m *Entity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Entity.Marshal(b, m, deterministic)
}
func (m *Entity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Entity.Merge(m, src)
}
func (m *Entity) XXX_Size() int {
	return xxx_messageInfo_Entity.Size(m)
}
func (m *Entity) XXX_DiscardUnknown() {
	xxx_messageInfo_Entity.DiscardUnknown(m)
}

var xxx_messageInfo_Entity proto.InternalMessageInfo

func (m *Entity) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func (m *Entity) GetClass() uint64 {
	if m != nil {
		return m.Class
	}
	return 0
}

func (m *Entity) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Entity) GetComponents() []*Component {
	if m != nil {
		return m.Components
	}
	return nil
}

func init() {
	proto.RegisterType((*Entity)(nil), "entity.Entity")
}

func init() { proto.RegisterFile("entity.proto", fileDescriptor_cf50d946d740d100) }

var fileDescriptor_cf50d946d740d100 = []byte{
	// 138 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0xcd, 0x2b, 0xc9,
	0x2c, 0xa9, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x83, 0xf0, 0xa4, 0xf8, 0x93, 0xf3,
	0x73, 0x0b, 0xf2, 0xf3, 0x80, 0x3c, 0x88, 0x84, 0x52, 0x1d, 0x17, 0x9b, 0x2b, 0x58, 0x4a, 0x48,
	0x82, 0x8b, 0x3d, 0x35, 0x2f, 0x31, 0x29, 0x27, 0x35, 0x45, 0x82, 0x51, 0x81, 0x51, 0x83, 0x23,
	0x08, 0xc6, 0x15, 0x12, 0xe1, 0x62, 0x4d, 0xce, 0x49, 0x2c, 0x2e, 0x96, 0x60, 0x02, 0x8a, 0xb3,
	0x04, 0x41, 0x38, 0x42, 0x7c, 0x5c, 0x4c, 0x99, 0x29, 0x12, 0xcc, 0x60, 0x21, 0x20, 0x4b, 0xc8,
	0x84, 0x8b, 0x0b, 0x6e, 0x78, 0xb1, 0x04, 0x8b, 0x02, 0xb3, 0x06, 0xb7, 0x91, 0x88, 0x1e, 0xc2,
	0x3e, 0x67, 0x18, 0x2b, 0x08, 0x49, 0x5d, 0x12, 0x1b, 0xd8, 0x19, 0xc6, 0x80, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xa3, 0xc3, 0x5b, 0x6c, 0xaf, 0x00, 0x00, 0x00,
}
